apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: drone-pg-cluster
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi

  # 'app' user will be created with connection details in a secret
  # named {cluster-name}-app
  bootstrap:
    initdb:
      database: dronedata
      owner: app
      postInitApplicationSQL:
        - |
          CREATE TABLE IF NOT EXISTS coordinates (
            id SERIAL PRIMARY KEY,
            drone_id VARCHAR(50),
            latitude FLOAT,
            longitude FLOAT,
            created_at TIMESTAMP DEFAULT NOW()
          );
          CREATE TABLE IF NOT EXISTS battery_logs (
            id SERIAL PRIMARY KEY,
            drone_id VARCHAR(50),
            battery_level INT,
            created_at TIMESTAMP DEFAULT NOW()
          );